// Pure report-builder helpers: slug, header/TOC/footer HTML, and the
// enabled-module filter. Extracted (logic-identical) from app-core.js
// #region REPORTS & XLSX; the modal / DOM / PNG-capture code stays in app-core
// and calls these via window. Pinned by tests/unit/report-view.test.mjs.

import { esc } from './utils.js';

export function rptSlugify(str){
  return String(str||'report').toLowerCase()
    .replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60);
}

export function buildReportHeader(state){
  var title=esc(state.title||'AWS Infrastructure Assessment');
  var author=esc(state.author||'');
  var date=esc(state.date||'');
  var sub=[];
  if(author) sub.push(author);
  if(date) sub.push(date);
  var logoHtml='';
  if(state.logo&&state.logo.dataUri){
    logoHtml='<div class="rpt-logo"><img src="'+state.logo.dataUri+'" alt="Logo" style="max-height:60px;max-width:200px;object-fit:contain"></div>';
  }
  return '<div class="rpt-header">'+logoHtml+'<h1>'+title+'</h1>'+
    (sub.length?'<div class="subtitle">'+sub.join(' &mdash; ')+'</div>':'')+
    '</div>';
}

export function buildReportTOC(enabled, modules){
  var h='<div class="rpt-toc"><h2>Table of Contents</h2>';
  enabled.forEach(function(id,i){
    var m=modules.find(function(x){return x.id===id});
    h+='<a href="#s-'+esc(id)+'">'+(i+1)+'. '+esc(m.name)+'</a>';
  });
  h+='</div>';
  return h;
}

export function buildReportFooter(nowStr){
  return '<div class="rpt-footer-bar">Generated by AWS Mapper &mdash; '+esc(nowStr)+'</div>';
}

export function enabledReportModules(modules, order){
  var ord=order||modules.map(function(m){return m.id});
  return ord.filter(function(id){
    var m=modules.find(function(x){return x.id===id});
    return m&&m.enabled&&m.available();
  });
}
