/**
 * IaC Export Generators — Terraform HCL + CloudFormation YAML/JSON
 * Extracted from app-core.js lines 26329-27574
 * Pure functions: receive ctx/opts, return result objects.
 */

/* globals gn, esc, _cfnTags */

function _sanitizeName(s){
  if(!s)return 'unnamed';
  return s.replace(/[^a-zA-Z0-9_-]/g,'_').replace(/^[0-9]/,'r$&').replace(/-/g,'_').toLowerCase();
}

function _tfName(resource,prefix){
  const n=resource.Tags&&resource.Tags.find(t=>t.Key==='Name');
  const raw=n?n.Value:(resource.VpcId||resource.SubnetId||resource.GroupId||resource.InstanceId||prefix||'res');
  return _sanitizeName(raw);
}

// --- ID -> TF resource name maps (built during generation) ---
let _tfIdMap={};

function _tfRef(id,attr){
  if(_tfIdMap[id])return _tfIdMap[id]+'.'+attr;
  return '"'+id+'"';
}

// --- Circular SG detection ---
function detectCircularSGs(sgs){
  const graph={};
  sgs.forEach(sg=>{
    graph[sg.GroupId]=new Set();
    (sg.IpPermissions||[]).concat(sg.IpPermissionsEgress||[]).forEach(rule=>{
      (rule.UserIdGroupPairs||[]).forEach(pair=>{
        if(pair.GroupId&&pair.GroupId!==sg.GroupId)graph[sg.GroupId].add(pair.GroupId);
      });
    });
  });
  const cycles=[];
  const visited=new Set(),inStack=new Set();
  function dfs(node,path){
    if(inStack.has(node)){
      const ci=path.indexOf(node);
      if(ci>=0)cycles.push(path.slice(ci));
      return;
    }
    if(visited.has(node))return;
    visited.add(node);inStack.add(node);path.push(node);
    (graph[node]||new Set()).forEach(nb=>dfs(nb,[...path]));
    inStack.delete(node);
  }
  Object.keys(graph).forEach(n=>{if(!visited.has(n))dfs(n,[])});
  return cycles;
}

// --- HCL Generation ---
function generateTerraform(ctx,opts){
  if(!ctx||!ctx.vpcs)return '# No data loaded';
  _tfIdMap={};
  const lines=[];
  const vars=[];
  const imports=[];
  const warnings=[];
  const mode=opts.mode||'import';
  const scopeVpc=opts.scopeVpcId||null;
  const includeVars=opts.includeVars!==false;

  // Filter by scope
  const vpcs=scopeVpc?ctx.vpcs.filter(v=>v.VpcId===scopeVpc):ctx.vpcs;
  const vpcIds=new Set(vpcs.map(v=>v.VpcId));
  const subnets=(ctx.subnets||[]).filter(s=>vpcIds.has(s.VpcId));
  const subIds=new Set(subnets.map(s=>s.SubnetId));
  const sgs=(ctx.sgs||[]).filter(s=>vpcIds.has(s.VpcId));
  const rts=(ctx.rts||[]).filter(r=>{const assoc=(r.Associations||[]); return assoc.some(a=>vpcIds.has(a.SubnetId?subnets.find(s=>s.SubnetId===a.SubnetId)?.VpcId:null))||vpcIds.has(r.VpcId)});
  const nacls=(ctx.nacls||[]).filter(n=>vpcIds.has(n.VpcId));
  const igws=(ctx.igws||[]).filter(g=>(g.Attachments||[]).some(a=>vpcIds.has(a.VpcId)));
  const nats=(ctx.nats||[]).filter(n=>vpcIds.has(n.VpcId));
  const vpces=(ctx.vpces||[]).filter(v=>vpcIds.has(v.VpcId));
  const instances=(ctx.instances||[]).filter(i=>subIds.has(i.SubnetId));
  const rdsInstances=(ctx.rdsInstances||[]).filter(r=>{const sn=r.DBSubnetGroup;return sn&&(sn.Subnets||[]).some(s=>subIds.has(s.SubnetIdentifier))});
  const lambdaFns=(ctx.lambdaFns||[]).filter(l=>{const vc=l.VpcConfig;return vc&&(vc.SubnetIds||[]).some(s=>subIds.has(s))});
  const ecsServices=(ctx.ecsServices||[]).filter(e=>{const nc=(e.networkConfiguration||{}).awsvpcConfiguration;return nc&&(nc.subnets||[]).some(s=>subIds.has(s))});
  const ecacheClusters=(ctx.ecacheClusters||[]).filter(c=>c.CacheSubnetGroupName);
  const redshiftClusters=(ctx.redshiftClusters||[]).filter(c=>c.ClusterSubnetGroupName);
  const albs=(ctx.albs||[]).filter(a=>(a.AvailabilityZones||[]).some(az=>subIds.has(az.SubnetId)));
  const volumes=(ctx.volumes||[]).filter(v=>v.Attachments&&v.Attachments.some(a=>instances.find(i=>i.InstanceId===a.InstanceId)));
  const s3bk=scopeVpc?[]:(ctx.s3bk||[]);
  const peerings=(ctx.peerings||[]).filter(p=>{const a=p.AccepterVpcInfo,r=p.RequesterVpcInfo;return(a&&vpcIds.has(a.VpcId))||(r&&vpcIds.has(r.VpcId))});
  const cfDistributions=scopeVpc?[]:(ctx.cfDistributions||[]);

  // Header
  lines.push('# Generated by AWS Mapper');
  lines.push('# Date: '+new Date().toISOString().split('T')[0]);
  lines.push('# Mode: '+(mode==='import'?'Import Existing':mode==='create'?'Create New':'Full Recreate'));
  lines.push('#');
  lines.push('# KNOWN LIMITATIONS - Review before applying:');
  lines.push('# - AMI IDs are region-specific and may need updating');
  lines.push('# - Key pair names must exist in the target account');
  lines.push('# - IAM roles/instance profiles are not included');
  lines.push('# - Passwords and secrets are placeholder values');
  lines.push('# - Custom DNS/DHCP options may need manual configuration');
  lines.push('');

  // Provider
  lines.push('terraform {');
  lines.push('  required_providers {');
  lines.push('    aws = {');
  lines.push('      source  = "hashicorp/aws"');
  lines.push('      version = "~> 5.0"');
  lines.push('    }');
  lines.push('  }');
  lines.push('}');
  lines.push('');
  lines.push('provider "aws" {');
  lines.push('  region = var.aws_region');
  lines.push('');
  lines.push('  default_tags {');
  lines.push('    tags = {');
  lines.push('      ManagedBy   = "terraform"');
  lines.push('      GeneratedBy = "aws-mapper"');
  lines.push('    }');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  // Variables
  if(includeVars){
    const region=subnets.length&&subnets[0].AvailabilityZone?subnets[0].AvailabilityZone.replace(/[a-z]$/,''):'us-east-1';
    vars.push({name:'aws_region',desc:'AWS Region',type:'string',def:region});
    const cidrs=new Set(vpcs.map(v=>v.CidrBlock));
    if(cidrs.size)vars.push({name:'vpc_cidrs',desc:'VPC CIDR blocks',type:'map(string)',def:null});
    const azs=new Set(subnets.map(s=>s.AvailabilityZone).filter(Boolean));
    if(azs.size)vars.push({name:'availability_zones',desc:'Availability zones',type:'list(string)',def:[...azs]});
    const iTypes=new Set(instances.map(i=>i.InstanceType).filter(Boolean));
    if(iTypes.size)vars.push({name:'instance_types',desc:'EC2 instance types in use',type:'map(string)',def:null});
  }

  vars.forEach(v=>{
    lines.push('variable "'+v.name+'" {');
    lines.push('  description = "'+v.desc+'"');
    lines.push('  type        = '+v.type);
    if(v.def!==null&&v.def!==undefined){
      if(Array.isArray(v.def)){
        lines.push('  default     = '+JSON.stringify(v.def));
      }else{
        lines.push('  default     = "'+v.def+'"');
      }
    }
    lines.push('}');
    lines.push('');
  });

  // Detect circular SGs
  const sgCycles=detectCircularSGs(sgs);
  const cyclicSgIds=new Set();
  sgCycles.forEach(c=>c.forEach(id=>cyclicSgIds.add(id)));

  // --- VPCs ---
  vpcs.forEach(vpc=>{
    const name=_tfName(vpc,'vpc');
    const resName='aws_vpc.'+name;
    _tfIdMap[vpc.VpcId]=resName;
    if(mode==='import')imports.push({to:resName,id:vpc.VpcId});
    lines.push('# VPC: '+(vpc.Tags&&vpc.Tags.find(t=>t.Key==='Name')?vpc.Tags.find(t=>t.Key==='Name').Value:vpc.VpcId));
    lines.push('resource "aws_vpc" "'+name+'" {');
    lines.push('  cidr_block           = "'+vpc.CidrBlock+'"');
    lines.push('  enable_dns_support   = '+(vpc.EnableDnsSupport!==false?'true':'false'));
    lines.push('  enable_dns_hostnames = '+(vpc.EnableDnsHostnames===true?'true':'false'));
    if(vpc.InstanceTenancy&&vpc.InstanceTenancy!=='default')lines.push('  instance_tenancy     = "'+vpc.InstanceTenancy+'"');
    _writeTags(lines,vpc);
    lines.push('}');
    lines.push('');
  });

  // --- IGWs ---
  igws.forEach(igw=>{
    const name=_tfName(igw,'igw');
    const resName='aws_internet_gateway.'+name;
    _tfIdMap[igw.InternetGatewayId]=resName;
    if(mode==='import')imports.push({to:resName,id:igw.InternetGatewayId});
    lines.push('resource "aws_internet_gateway" "'+name+'" {');
    const att=(igw.Attachments||[])[0];
    if(att)lines.push('  vpc_id = '+_tfRef(att.VpcId,'id'));
    _writeTags(lines,igw);
    lines.push('}');
    lines.push('');
  });

  // --- Subnets ---
  subnets.forEach(sub=>{
    const name=_tfName(sub,'subnet');
    const resName='aws_subnet.'+name;
    _tfIdMap[sub.SubnetId]=resName;
    if(mode==='import')imports.push({to:resName,id:sub.SubnetId});
    lines.push('resource "aws_subnet" "'+name+'" {');
    lines.push('  vpc_id            = '+_tfRef(sub.VpcId,'id'));
    lines.push('  cidr_block        = "'+sub.CidrBlock+'"');
    if(sub.AvailabilityZone)lines.push('  availability_zone = "'+sub.AvailabilityZone+'"');
    if(sub.MapPublicIpOnLaunch)lines.push('  map_public_ip_on_launch = true');
    _writeTags(lines,sub);
    lines.push('}');
    lines.push('');
  });

  // --- Route Tables ---
  rts.forEach(rt=>{
    const name=_tfName(rt,'rt');
    const resName='aws_route_table.'+name;
    _tfIdMap[rt.RouteTableId]=resName;
    if(mode==='import')imports.push({to:resName,id:rt.RouteTableId});
    const vpcId=rt.VpcId||(rt.Associations&&rt.Associations[0]?rt.Associations[0].VpcId:null);
    lines.push('resource "aws_route_table" "'+name+'" {');
    if(vpcId)lines.push('  vpc_id = '+_tfRef(vpcId,'id'));
    (rt.Routes||[]).forEach(route=>{
      if(route.GatewayId==='local')return;
      lines.push('');
      lines.push('  route {');
      if(route.DestinationCidrBlock)lines.push('    cidr_block = "'+route.DestinationCidrBlock+'"');
      if(route.GatewayId&&route.GatewayId!=='local')lines.push('    gateway_id = '+_tfRef(route.GatewayId,'id'));
      if(route.NatGatewayId)lines.push('    nat_gateway_id = '+_tfRef(route.NatGatewayId,'id'));
      if(route.VpcPeeringConnectionId)lines.push('    vpc_peering_connection_id = '+_tfRef(route.VpcPeeringConnectionId,'id'));
      if(route.TransitGatewayId)lines.push('    transit_gateway_id = "'+route.TransitGatewayId+'"');
      if(route.VpcEndpointId)lines.push('    vpc_endpoint_id = '+_tfRef(route.VpcEndpointId,'id'));
      lines.push('  }');
    });
    _writeTags(lines,rt);
    lines.push('}');
    lines.push('');
    // RT associations
    (rt.Associations||[]).forEach((assoc,ai)=>{
      if(assoc.Main)return;
      if(!assoc.SubnetId)return;
      const aname=name+'_assoc_'+ai;
      lines.push('resource "aws_route_table_association" "'+aname+'" {');
      lines.push('  subnet_id      = '+_tfRef(assoc.SubnetId,'id'));
      lines.push('  route_table_id = '+_tfRef(rt.RouteTableId,'id'));
      lines.push('}');
      lines.push('');
    });
  });

  // --- NAT Gateways ---
  nats.forEach(nat=>{
    const name=_tfName(nat,'nat');
    const resName='aws_nat_gateway.'+name;
    _tfIdMap[nat.NatGatewayId]=resName;
    if(mode==='import')imports.push({to:resName,id:nat.NatGatewayId});
    lines.push('resource "aws_nat_gateway" "'+name+'" {');
    if(nat.SubnetId)lines.push('  subnet_id     = '+_tfRef(nat.SubnetId,'id'));
    const eip=(nat.NatGatewayAddresses||[])[0];
    if(eip&&eip.AllocationId)lines.push('  allocation_id = "'+eip.AllocationId+'" # EIP allocation');
    lines.push('  connectivity_type = "'+(nat.ConnectivityType||'public')+'"');
    _writeTags(lines,nat);
    lines.push('}');
    lines.push('');
  });

  // --- Security Groups ---
  sgs.forEach(sg=>{
    const name=_tfName(sg,'sg');
    const resName='aws_security_group.'+name;
    _tfIdMap[sg.GroupId]=resName;
    if(mode==='import')imports.push({to:resName,id:sg.GroupId});
    const isCyclic=cyclicSgIds.has(sg.GroupId);
    if(isCyclic)lines.push('# Circular SG reference detected - rules split into separate resources');
    lines.push('resource "aws_security_group" "'+name+'" {');
    lines.push('  name        = "'+(sg.GroupName||name)+'"');
    lines.push('  description = "'+(sg.Description||'Managed by Terraform')+'"');
    if(sg.VpcId)lines.push('  vpc_id      = '+_tfRef(sg.VpcId,'id'));
    if(!isCyclic){
      (sg.IpPermissions||[]).forEach(rule=>{
        lines.push('');
        lines.push('  ingress {');
        _writeSGRule(lines,rule);
        lines.push('  }');
      });
      (sg.IpPermissionsEgress||[]).forEach(rule=>{
        lines.push('');
        lines.push('  egress {');
        _writeSGRule(lines,rule);
        lines.push('  }');
      });
    }
    _writeTags(lines,sg);
    lines.push('}');
    lines.push('');
    // Split rules for cyclic SGs
    if(isCyclic){
      (sg.IpPermissions||[]).forEach((rule,ri)=>{
        lines.push('resource "aws_security_group_rule" "'+name+'_ingress_'+ri+'" {');
        lines.push('  type              = "ingress"');
        lines.push('  security_group_id = '+_tfRef(sg.GroupId,'id'));
        _writeSGRuleFlat(lines,rule);
        lines.push('}');
        lines.push('');
      });
      (sg.IpPermissionsEgress||[]).forEach((rule,ri)=>{
        lines.push('resource "aws_security_group_rule" "'+name+'_egress_'+ri+'" {');
        lines.push('  type              = "egress"');
        lines.push('  security_group_id = '+_tfRef(sg.GroupId,'id'));
        _writeSGRuleFlat(lines,rule);
        lines.push('}');
        lines.push('');
      });
    }
  });

  // --- NACLs ---
  nacls.forEach(nacl=>{
    const name=_tfName(nacl,'nacl');
    const resName='aws_network_acl.'+name;
    _tfIdMap[nacl.NetworkAclId]=resName;
    if(mode==='import')imports.push({to:resName,id:nacl.NetworkAclId});
    lines.push('resource "aws_network_acl" "'+name+'" {');
    if(nacl.VpcId)lines.push('  vpc_id     = '+_tfRef(nacl.VpcId,'id'));
    const assocSubs=(nacl.Associations||[]).map(a=>a.SubnetId).filter(Boolean);
    if(assocSubs.length)lines.push('  subnet_ids = ['+assocSubs.map(s=>_tfRef(s,'id')).join(', ')+']');
    (nacl.Entries||[]).forEach(entry=>{
      if(entry.RuleNumber===32767)return; // default deny
      const dir=entry.Egress?'egress':'ingress';
      lines.push('');
      lines.push('  '+dir+' {');
      lines.push('    rule_no    = '+entry.RuleNumber);
      lines.push('    protocol   = "'+entry.Protocol+'"');
      lines.push('    action     = "'+(entry.RuleAction||'allow')+'"');
      if(entry.CidrBlock)lines.push('    cidr_block = "'+entry.CidrBlock+'"');
      if(entry.PortRange){
        lines.push('    from_port  = '+(entry.PortRange.From||0));
        lines.push('    to_port    = '+(entry.PortRange.To||0));
      }
      lines.push('  }');
    });
    _writeTags(lines,nacl);
    lines.push('}');
    lines.push('');
  });

  // --- VPC Endpoints ---
  vpces.forEach(vpce=>{
    const name=_tfName(vpce,'vpce');
    const resName='aws_vpc_endpoint.'+name;
    _tfIdMap[vpce.VpcEndpointId]=resName;
    if(mode==='import')imports.push({to:resName,id:vpce.VpcEndpointId});
    lines.push('resource "aws_vpc_endpoint" "'+name+'" {');
    if(vpce.VpcId)lines.push('  vpc_id            = '+_tfRef(vpce.VpcId,'id'));
    if(vpce.ServiceName)lines.push('  service_name      = "'+vpce.ServiceName+'"');
    if(vpce.VpcEndpointType)lines.push('  vpc_endpoint_type = "'+vpce.VpcEndpointType+'"');
    if(vpce.VpcEndpointType==='Interface'&&vpce.SubnetIds&&vpce.SubnetIds.length){
      lines.push('  subnet_ids        = ['+vpce.SubnetIds.map(s=>_tfRef(s,'id')).join(', ')+']');
    }
    if(vpce.RouteTableIds&&vpce.RouteTableIds.length){
      lines.push('  route_table_ids   = ['+vpce.RouteTableIds.map(r=>_tfRef(r,'id')).join(', ')+']');
    }
    _writeTags(lines,vpce);
    lines.push('}');
    lines.push('');
  });

  // --- EC2 Instances ---
  instances.forEach(inst=>{
    const name=_tfName(inst,'ec2');
    const resName='aws_instance.'+name;
    _tfIdMap[inst.InstanceId]=resName;
    if(mode==='import')imports.push({to:resName,id:inst.InstanceId});
    lines.push('resource "aws_instance" "'+name+'" {');
    if(inst.ImageId)lines.push('  ami           = "'+inst.ImageId+'" # WARNING: AMI is region-specific');
    if(inst.InstanceType)lines.push('  instance_type = "'+inst.InstanceType+'"');
    if(inst.SubnetId)lines.push('  subnet_id     = '+_tfRef(inst.SubnetId,'id'));
    if(inst.KeyName)lines.push('  key_name      = "'+inst.KeyName+'" # Must exist in target account');
    const sgIds=(inst.SecurityGroups||inst.NetworkInterfaces&&inst.NetworkInterfaces[0]&&inst.NetworkInterfaces[0].Groups||[]).map(g=>g.GroupId).filter(Boolean);
    if(sgIds.length)lines.push('  vpc_security_group_ids = ['+sgIds.map(s=>_tfRef(s,'id')).join(', ')+']');
    if(inst.IamInstanceProfile&&inst.IamInstanceProfile.Arn){
      lines.push('  iam_instance_profile = "'+inst.IamInstanceProfile.Arn.split('/').pop()+'" # IAM profile must exist');
    }
    if(inst.Placement&&inst.Placement.Tenancy&&inst.Placement.Tenancy!=='default'){
      lines.push('  tenancy = "'+inst.Placement.Tenancy+'"');
    }
    _writeTags(lines,inst);
    lines.push('}');
    lines.push('');
  });

  // --- EBS Volumes ---
  volumes.forEach(vol=>{
    const name=_tfName(vol,'vol');
    const resName='aws_ebs_volume.'+name;
    _tfIdMap[vol.VolumeId]=resName;
    if(mode==='import')imports.push({to:resName,id:vol.VolumeId});
    lines.push('resource "aws_ebs_volume" "'+name+'" {');
    if(vol.AvailabilityZone)lines.push('  availability_zone = "'+vol.AvailabilityZone+'"');
    if(vol.Size)lines.push('  size              = '+vol.Size);
    if(vol.VolumeType)lines.push('  type              = "'+vol.VolumeType+'"');
    if(vol.Iops&&(vol.VolumeType==='io1'||vol.VolumeType==='io2'||vol.VolumeType==='gp3'))lines.push('  iops              = '+vol.Iops);
    if(vol.Encrypted)lines.push('  encrypted         = true');
    _writeTags(lines,vol);
    lines.push('}');
    lines.push('');
  });

  // --- ALBs ---
  albs.forEach(alb=>{
    const name=_tfName(alb,'alb');
    const type=alb.Type||'application';
    const resType=type==='network'?'aws_lb':'aws_lb';
    const resName=resType+'.'+name;
    _tfIdMap[alb.LoadBalancerArn]=resName;
    if(mode==='import')imports.push({to:resName,id:alb.LoadBalancerArn});
    lines.push('resource "'+resType+'" "'+name+'" {');
    if(alb.LoadBalancerName)lines.push('  name               = "'+alb.LoadBalancerName+'"');
    lines.push('  load_balancer_type = "'+type+'"');
    lines.push('  internal           = '+(alb.Scheme==='internal'?'true':'false'));
    const albSubs=(alb.AvailabilityZones||[]).map(az=>az.SubnetId).filter(Boolean);
    if(albSubs.length)lines.push('  subnets            = ['+albSubs.map(s=>_tfRef(s,'id')).join(', ')+']');
    const albSgs=(alb.SecurityGroups||[]);
    if(albSgs.length)lines.push('  security_groups    = ['+albSgs.map(s=>_tfRef(s,'id')).join(', ')+']');
    _writeTags(lines,alb);
    lines.push('}');
    lines.push('');
  });

  // --- RDS Instances ---
  rdsInstances.forEach(rds=>{
    const name=_sanitizeName(rds.DBInstanceIdentifier||'rds');
    const resName='aws_db_instance.'+name;
    _tfIdMap[rds.DBInstanceIdentifier]=resName;
    if(mode==='import')imports.push({to:resName,id:rds.DBInstanceIdentifier});
    lines.push('resource "aws_db_instance" "'+name+'" {');
    if(rds.DBInstanceIdentifier)lines.push('  identifier     = "'+rds.DBInstanceIdentifier+'"');
    if(rds.Engine)lines.push('  engine         = "'+rds.Engine+'"');
    if(rds.EngineVersion)lines.push('  engine_version = "'+rds.EngineVersion+'"');
    if(rds.DBInstanceClass)lines.push('  instance_class = "'+rds.DBInstanceClass+'"');
    if(rds.AllocatedStorage)lines.push('  allocated_storage = '+rds.AllocatedStorage);
    if(rds.StorageType)lines.push('  storage_type   = "'+rds.StorageType+'"');
    if(rds.MultiAZ)lines.push('  multi_az       = true');
    if(rds.StorageEncrypted)lines.push('  storage_encrypted = true');
    if(rds.DBSubnetGroup&&rds.DBSubnetGroup.DBSubnetGroupName){
      lines.push('  db_subnet_group_name = "'+rds.DBSubnetGroup.DBSubnetGroupName+'"');
    }
    const rdsSgs=(rds.VpcSecurityGroups||[]).map(s=>s.VpcSecurityGroupId).filter(Boolean);
    if(rdsSgs.length)lines.push('  vpc_security_group_ids = ['+rdsSgs.map(s=>_tfRef(s,'id')).join(', ')+']');
    lines.push('  username         = "admin" # PLACEHOLDER - set actual username');
    lines.push('  password         = "CHANGE_ME" # PLACEHOLDER - use secrets manager');
    lines.push('  skip_final_snapshot = true');
    lines.push('}');
    lines.push('');
  });

  // --- ElastiCache ---
  ecacheClusters.forEach(ec=>{
    const name=_sanitizeName(ec.CacheClusterId||'cache');
    const resName='aws_elasticache_cluster.'+name;
    _tfIdMap[ec.CacheClusterId]=resName;
    if(mode==='import')imports.push({to:resName,id:ec.CacheClusterId});
    lines.push('resource "aws_elasticache_cluster" "'+name+'" {');
    if(ec.CacheClusterId)lines.push('  cluster_id      = "'+ec.CacheClusterId+'"');
    if(ec.Engine)lines.push('  engine          = "'+ec.Engine+'"');
    if(ec.CacheNodeType)lines.push('  node_type       = "'+ec.CacheNodeType+'"');
    if(ec.NumCacheNodes)lines.push('  num_cache_nodes = '+ec.NumCacheNodes);
    if(ec.EngineVersion)lines.push('  engine_version  = "'+ec.EngineVersion+'"');
    if(ec.CacheSubnetGroupName)lines.push('  subnet_group_name = "'+ec.CacheSubnetGroupName+'"');
    const ecSgs=(ec.SecurityGroups||[]).map(s=>s.SecurityGroupId).filter(Boolean);
    if(ecSgs.length)lines.push('  security_group_ids = ['+ecSgs.map(s=>_tfRef(s,'id')).join(', ')+']');
    lines.push('}');
    lines.push('');
  });

  // --- Redshift ---
  redshiftClusters.forEach(rs=>{
    const name=_sanitizeName(rs.ClusterIdentifier||'redshift');
    const resName='aws_redshift_cluster.'+name;
    _tfIdMap[rs.ClusterIdentifier]=resName;
    if(mode==='import')imports.push({to:resName,id:rs.ClusterIdentifier});
    lines.push('resource "aws_redshift_cluster" "'+name+'" {');
    if(rs.ClusterIdentifier)lines.push('  cluster_identifier  = "'+rs.ClusterIdentifier+'"');
    if(rs.NodeType)lines.push('  node_type           = "'+rs.NodeType+'"');
    if(rs.NumberOfNodes>1)lines.push('  number_of_nodes     = '+rs.NumberOfNodes);
    lines.push('  cluster_type        = "'+(rs.NumberOfNodes>1?'multi-node':'single-node')+'"');
    if(rs.DBName)lines.push('  database_name       = "'+rs.DBName+'"');
    lines.push('  master_username     = "admin" # PLACEHOLDER');
    lines.push('  master_password     = "CHANGE_ME" # PLACEHOLDER');
    if(rs.ClusterSubnetGroupName)lines.push('  cluster_subnet_group_name = "'+rs.ClusterSubnetGroupName+'"');
    const rsSgs=(rs.VpcSecurityGroups||[]).map(s=>s.VpcSecurityGroupId).filter(Boolean);
    if(rsSgs.length)lines.push('  vpc_security_group_ids = ['+rsSgs.map(s=>_tfRef(s,'id')).join(', ')+']');
    lines.push('  skip_final_snapshot = true');
    lines.push('}');
    lines.push('');
  });

  // --- Lambda Functions ---
  lambdaFns.forEach(fn=>{
    const name=_sanitizeName(fn.FunctionName||'lambda');
    const resName='aws_lambda_function.'+name;
    _tfIdMap[fn.FunctionName]=resName;
    if(mode==='import')imports.push({to:resName,id:fn.FunctionName});
    lines.push('resource "aws_lambda_function" "'+name+'" {');
    if(fn.FunctionName)lines.push('  function_name = "'+fn.FunctionName+'"');
    if(fn.Runtime)lines.push('  runtime       = "'+fn.Runtime+'"');
    if(fn.Handler)lines.push('  handler       = "'+fn.Handler+'"');
    if(fn.MemorySize)lines.push('  memory_size   = '+fn.MemorySize);
    if(fn.Timeout)lines.push('  timeout       = '+fn.Timeout);
    lines.push('  role          = "arn:aws:iam::role/PLACEHOLDER" # Set actual IAM role ARN');
    lines.push('  filename      = "placeholder.zip" # Set actual deployment package');
    const vc=fn.VpcConfig;
    if(vc&&(vc.SubnetIds||[]).length){
      lines.push('');
      lines.push('  vpc_config {');
      lines.push('    subnet_ids         = ['+vc.SubnetIds.map(s=>_tfRef(s,'id')).join(', ')+']');
      if(vc.SecurityGroupIds&&vc.SecurityGroupIds.length)lines.push('    security_group_ids = ['+vc.SecurityGroupIds.map(s=>_tfRef(s,'id')).join(', ')+']');
      lines.push('  }');
    }
    lines.push('}');
    lines.push('');
  });

  // --- ECS Services ---
  ecsServices.forEach(svc=>{
    const name=_sanitizeName(svc.serviceName||'ecs');
    lines.push('# ECS Service: '+svc.serviceName);
    lines.push('# NOTE: ECS services require cluster and task definition resources');
    lines.push('# which are not captured in network-level data. Skeleton below.');
    lines.push('resource "aws_ecs_service" "'+name+'" {');
    if(svc.serviceName)lines.push('  name            = "'+svc.serviceName+'"');
    lines.push('  cluster         = "PLACEHOLDER" # Set actual cluster ARN');
    lines.push('  task_definition = "PLACEHOLDER" # Set actual task definition');
    if(svc.desiredCount)lines.push('  desired_count   = '+svc.desiredCount);
    if(svc.launchType)lines.push('  launch_type     = "'+svc.launchType+'"');
    const nc=(svc.networkConfiguration||{}).awsvpcConfiguration;
    if(nc){
      lines.push('');
      lines.push('  network_configuration {');
      if(nc.subnets&&nc.subnets.length)lines.push('    subnets          = ['+nc.subnets.map(s=>_tfRef(s,'id')).join(', ')+']');
      if(nc.securityGroups&&nc.securityGroups.length)lines.push('    security_groups  = ['+nc.securityGroups.map(s=>_tfRef(s,'id')).join(', ')+']');
      if(nc.assignPublicIp)lines.push('    assign_public_ip = '+(nc.assignPublicIp==='ENABLED'?'true':'false'));
      lines.push('  }');
    }
    lines.push('}');
    lines.push('');
  });

  // --- S3 Buckets ---
  s3bk.forEach(bk=>{
    const name=_sanitizeName(bk.Name||'bucket');
    const resName='aws_s3_bucket.'+name;
    _tfIdMap[bk.Name]=resName;
    if(mode==='import')imports.push({to:resName,id:bk.Name});
    lines.push('resource "aws_s3_bucket" "'+name+'" {');
    if(bk.Name)lines.push('  bucket = "'+bk.Name+'"');
    lines.push('}');
    lines.push('');
  });

  // --- VPC Peering ---
  peerings.forEach(peer=>{
    const name=_sanitizeName(peer.VpcPeeringConnectionId||'peer');
    const resName='aws_vpc_peering_connection.'+name;
    _tfIdMap[peer.VpcPeeringConnectionId]=resName;
    if(mode==='import')imports.push({to:resName,id:peer.VpcPeeringConnectionId});
    lines.push('resource "aws_vpc_peering_connection" "'+name+'" {');
    const req=peer.RequesterVpcInfo,acc=peer.AccepterVpcInfo;
    if(req&&req.VpcId)lines.push('  vpc_id      = '+_tfRef(req.VpcId,'id'));
    if(acc&&acc.VpcId)lines.push('  peer_vpc_id = '+_tfRef(acc.VpcId,'id'));
    if(acc&&acc.OwnerId)lines.push('  peer_owner_id = "'+acc.OwnerId+'"');
    if(acc&&acc.Region)lines.push('  peer_region   = "'+acc.Region+'"');
    lines.push('  auto_accept = false # Set to true for same-account peering');
    lines.push('}');
    lines.push('');
  });

  // --- CloudFront ---
  cfDistributions.forEach(cf=>{
    const name=_sanitizeName(cf.Id||'cf');
    lines.push('# CloudFront Distribution: '+(cf.DomainName||cf.Id));
    lines.push('# NOTE: CloudFront has many configuration options not captured here.');
    lines.push('# This is a skeleton. Review and customize before applying.');
    lines.push('resource "aws_cloudfront_distribution" "'+name+'" {');
    lines.push('  enabled = '+(cf.Enabled!==false?'true':'false'));
    if(cf.Comment)lines.push('  comment = "'+cf.Comment.replace(/\\/g,'\\\\').replace(/"/g,'\\"')+'"');
    lines.push('');
    lines.push('  origin {');
    lines.push('    domain_name = "PLACEHOLDER.s3.amazonaws.com"');
    lines.push('    origin_id   = "S3-origin"');
    lines.push('  }');
    lines.push('');
    lines.push('  default_cache_behavior {');
    lines.push('    allowed_methods        = ["GET", "HEAD"]');
    lines.push('    cached_methods         = ["GET", "HEAD"]');
    lines.push('    target_origin_id       = "S3-origin"');
    lines.push('    viewer_protocol_policy = "redirect-to-https"');
    lines.push('');
    lines.push('    forwarded_values {');
    lines.push('      query_string = false');
    lines.push('      cookies { forward = "none" }');
    lines.push('    }');
    lines.push('  }');
    lines.push('');
    lines.push('  restrictions {');
    lines.push('    geo_restriction { restriction_type = "none" }');
    lines.push('  }');
    lines.push('');
    lines.push('  viewer_certificate { cloudfront_default_certificate = true }');
    lines.push('}');
    lines.push('');
  });

  // --- Import blocks (Terraform 1.5+) ---
  if(mode==='import'&&imports.length){
    lines.push('');
    lines.push('# === Import Blocks (Terraform 1.5+) ===');
    lines.push('# Run: terraform plan to verify imports match existing state');
    lines.push('');
    imports.forEach(imp=>{
      lines.push('import {');
      lines.push('  to = '+imp.to);
      lines.push('  id = "'+imp.id+'"');
      lines.push('}');
      lines.push('');
    });
  }

  // Warnings
  if(instances.some(i=>i.ImageId))warnings.push('AMI IDs are region-specific. Update for target region.');
  if(instances.some(i=>i.KeyName))warnings.push('Key pair names must exist in the target account.');
  if(rdsInstances.length||redshiftClusters.length)warnings.push('Database passwords are placeholders. Use AWS Secrets Manager.');
  if(sgCycles.length)warnings.push(sgCycles.length+' circular SG reference(s) detected. Rules split into separate resources.');

  const code=lines.join('\n');
  return {code:code,warnings:warnings,stats:{vpcs:vpcs.length,subnets:subnets.length,sgs:sgs.length,instances:instances.length,total:imports.length||lines.filter(l=>l.startsWith('resource ')).length}};
}

function _writeTags(lines,resource){
  const tags=(resource.Tags||[]).filter(t=>t.Key!=='aws:');
  if(!tags.length)return;
  lines.push('');
  lines.push('  tags = {');
  tags.forEach(t=>{
    const k=t.Key.match(/^[a-zA-Z_][a-zA-Z0-9_]*$/)?t.Key:('"'+t.Key+'"');
    lines.push('    '+k+' = "'+((t.Value||'').replace(/\\/g,'\\\\').replace(/"/g,'\\"'))+'"');
  });
  lines.push('  }');
}

function _writeSGRule(lines,rule){
  const fromPort=rule.FromPort!=null?rule.FromPort:0;
  const toPort=rule.ToPort!=null?rule.ToPort:0;
  const proto=rule.IpProtocol||'-1';
  lines.push('    protocol    = "'+proto+'"');
  lines.push('    from_port   = '+fromPort);
  lines.push('    to_port     = '+toPort);
  const cidrs=(rule.IpRanges||[]).map(r=>r.CidrIp).filter(Boolean);
  const v6cidrs=(rule.Ipv6Ranges||[]).map(r=>r.CidrIpv6).filter(Boolean);
  const sgRefs=(rule.UserIdGroupPairs||[]).map(p=>p.GroupId).filter(Boolean);
  if(cidrs.length)lines.push('    cidr_blocks = '+JSON.stringify(cidrs));
  if(v6cidrs.length)lines.push('    ipv6_cidr_blocks = '+JSON.stringify(v6cidrs));
  if(sgRefs.length)lines.push('    security_groups = ['+sgRefs.map(s=>_tfRef(s,'id')).join(', ')+']');
  const desc=(rule.IpRanges||[]).find(r=>r.Description);
  if(desc)lines.push('    description = "'+(desc.Description||'').replace(/\\/g,'\\\\').replace(/"/g,'\\"')+'"');
}

function _writeSGRuleFlat(lines,rule){
  const fromPort=rule.FromPort!=null?rule.FromPort:0;
  const toPort=rule.ToPort!=null?rule.ToPort:0;
  const proto=rule.IpProtocol||'-1';
  lines.push('  protocol         = "'+proto+'"');
  lines.push('  from_port        = '+fromPort);
  lines.push('  to_port          = '+toPort);
  const cidrs=(rule.IpRanges||[]).map(r=>r.CidrIp).filter(Boolean);
  const sgRefs=(rule.UserIdGroupPairs||[]).map(p=>p.GroupId).filter(Boolean);
  if(cidrs.length)lines.push('  cidr_blocks      = '+JSON.stringify(cidrs));
  if(sgRefs.length&&sgRefs[0])lines.push('  source_security_group_id = '+_tfRef(sgRefs[0],'id'));
}

// --- CloudFormation Generation ---
function generateCloudFormation(ctx,opts){
  if(!ctx||!ctx.vpcs)return '# No data loaded';
  const scopeVpc=opts.scopeVpcId||null;
  const vpcs=scopeVpc?ctx.vpcs.filter(v=>v.VpcId===scopeVpc):ctx.vpcs;
  const vpcIds=new Set(vpcs.map(v=>v.VpcId));
  const subnets=(ctx.subnets||[]).filter(s=>vpcIds.has(s.VpcId));
  const subIds=new Set(subnets.map(s=>s.SubnetId));
  const sgs=(ctx.sgs||[]).filter(s=>vpcIds.has(s.VpcId));
  const igws=(ctx.igws||[]).filter(g=>(g.Attachments||[]).some(a=>vpcIds.has(a.VpcId)));
  const nats=(ctx.nats||[]).filter(n=>vpcIds.has(n.VpcId));
  const instances=(ctx.instances||[]).filter(i=>subIds.has(i.SubnetId));
  const rts=(ctx.rts||[]).filter(r=>r.VpcId&&vpcIds.has(r.VpcId));
  const rdsInstances=(ctx.rdsInstances||[]).filter(r=>{const sn=r.DBSubnetGroup;return sn&&(sn.Subnets||[]).some(s=>subIds.has(s.SubnetIdentifier))});
  const albs=(ctx.albs||[]).filter(a=>(a.AvailabilityZones||[]).some(az=>subIds.has(az.SubnetId)));

  const warnings=[];
  const totalResources=vpcs.length+subnets.length+sgs.length+igws.length+nats.length+instances.length+rts.length+rdsInstances.length+albs.length;
  if(totalResources>450)warnings.push('Resource count ('+totalResources+') approaches CloudFormation 500-resource limit. Consider nested stacks.');

  const template={
    AWSTemplateFormatVersion:'2010-09-09',
    Description:'Generated by AWS Mapper on '+new Date().toISOString().split('T')[0],
    Parameters:{},
    Resources:{},
    Outputs:{}
  };

  // ID to logical name map for Ref
  const cfnIdMap={};
  function cfnName(resource,prefix){
    const n=resource.Tags&&resource.Tags.find(t=>t.Key==='Name');
    const raw=n?n.Value:(prefix||'Res');
    return raw.replace(/[^a-zA-Z0-9]/g,'');
  }
  function cfnRef(id){
    if(cfnIdMap[id])return {'Ref':cfnIdMap[id]};
    return id;
  }

  // Parameters
  template.Parameters.AWSRegion={Type:'String',Default:subnets.length&&subnets[0].AvailabilityZone?subnets[0].AvailabilityZone.replace(/[a-z]$/,''):'us-east-1',Description:'AWS Region'};

  // VPCs
  vpcs.forEach(vpc=>{
    const ln=cfnName(vpc,'VPC');
    cfnIdMap[vpc.VpcId]=ln;
    template.Resources[ln]={
      Type:'AWS::EC2::VPC',
      Properties:{
        CidrBlock:vpc.CidrBlock,
        EnableDnsSupport:vpc.EnableDnsSupport!==false,
        EnableDnsHostnames:vpc.EnableDnsHostnames===true,
        Tags:_cfnTags(vpc)
      }
    };
  });

  // IGWs
  igws.forEach(igw=>{
    const ln=cfnName(igw,'IGW');
    cfnIdMap[igw.InternetGatewayId]=ln;
    template.Resources[ln]={Type:'AWS::EC2::InternetGateway',Properties:{Tags:_cfnTags(igw)}};
    const att=(igw.Attachments||[])[0];
    if(att){
      template.Resources[ln+'Attach']={
        Type:'AWS::EC2::VPCGatewayAttachment',
        Properties:{InternetGatewayId:{'Ref':ln},VpcId:cfnRef(att.VpcId)}
      };
    }
  });

  // Subnets
  subnets.forEach(sub=>{
    const ln=cfnName(sub,'Subnet');
    cfnIdMap[sub.SubnetId]=ln;
    const props={VpcId:cfnRef(sub.VpcId),CidrBlock:sub.CidrBlock,Tags:_cfnTags(sub)};
    if(sub.AvailabilityZone)props.AvailabilityZone=sub.AvailabilityZone;
    if(sub.MapPublicIpOnLaunch)props.MapPublicIpOnLaunch=true;
    template.Resources[ln]={Type:'AWS::EC2::Subnet',Properties:props};
  });

  // Route Tables
  rts.forEach(rt=>{
    const ln=cfnName(rt,'RT');
    cfnIdMap[rt.RouteTableId]=ln;
    template.Resources[ln]={Type:'AWS::EC2::RouteTable',Properties:{VpcId:cfnRef(rt.VpcId),Tags:_cfnTags(rt)}};
    (rt.Routes||[]).forEach((route,ri)=>{
      if(route.GatewayId==='local')return;
      const routeProps={RouteTableId:{'Ref':ln}};
      if(route.DestinationCidrBlock)routeProps.DestinationCidrBlock=route.DestinationCidrBlock;
      if(route.GatewayId&&route.GatewayId!=='local')routeProps.GatewayId=cfnRef(route.GatewayId);
      if(route.NatGatewayId)routeProps.NatGatewayId=cfnRef(route.NatGatewayId);
      template.Resources[ln+'Route'+ri]={Type:'AWS::EC2::Route',Properties:routeProps};
    });
    (rt.Associations||[]).forEach((assoc,ai)=>{
      if(assoc.Main||!assoc.SubnetId)return;
      template.Resources[ln+'Assoc'+ai]={
        Type:'AWS::EC2::SubnetRouteTableAssociation',
        Properties:{SubnetId:cfnRef(assoc.SubnetId),RouteTableId:{'Ref':ln}}
      };
    });
  });

  // NAT Gateways
  nats.forEach(nat=>{
    const ln=cfnName(nat,'NAT');
    cfnIdMap[nat.NatGatewayId]=ln;
    const props={SubnetId:cfnRef(nat.SubnetId),ConnectivityType:nat.ConnectivityType||'public'};
    const eip=(nat.NatGatewayAddresses||[])[0];
    if(eip&&eip.AllocationId)props.AllocationId=eip.AllocationId;
    template.Resources[ln]={Type:'AWS::EC2::NatGateway',Properties:props,DependsOn:Object.keys(template.Resources).filter(k=>k.endsWith('Attach'))};
  });

  // Security Groups
  const sgCycles=detectCircularSGs(sgs);
  const cyclicSgIds=new Set();
  sgCycles.forEach(c=>c.forEach(id=>cyclicSgIds.add(id)));

  sgs.forEach(sg=>{
    const ln=cfnName(sg,'SG');
    cfnIdMap[sg.GroupId]=ln;
    const isCyclic=cyclicSgIds.has(sg.GroupId);
    const props={GroupDescription:sg.Description||'Managed by CloudFormation',VpcId:cfnRef(sg.VpcId),Tags:_cfnTags(sg)};
    if(!isCyclic){
      if(sg.IpPermissions&&sg.IpPermissions.length)props.SecurityGroupIngress=sg.IpPermissions.map(_cfnSGRule);
      if(sg.IpPermissionsEgress&&sg.IpPermissionsEgress.length)props.SecurityGroupEgress=sg.IpPermissionsEgress.map(_cfnSGRule);
    }
    template.Resources[ln]={Type:'AWS::EC2::SecurityGroup',Properties:props};
    // Standalone rules for cyclic
    if(isCyclic){
      (sg.IpPermissions||[]).forEach((rule,ri)=>{
        const rProps=Object.assign({GroupId:{'Ref':ln},IpProtocol:rule.IpProtocol||'-1'},_cfnSGRuleProps(rule));
        template.Resources[ln+'Ingress'+ri]={Type:'AWS::EC2::SecurityGroupIngress',Properties:rProps};
      });
      (sg.IpPermissionsEgress||[]).forEach((rule,ri)=>{
        const rProps=Object.assign({GroupId:{'Ref':ln},IpProtocol:rule.IpProtocol||'-1'},_cfnSGRuleProps(rule));
        template.Resources[ln+'Egress'+ri]={Type:'AWS::EC2::SecurityGroupEgress',Properties:rProps};
      });
    }
  });

  // EC2 Instances
  instances.forEach(inst=>{
    const ln=cfnName(inst,'EC2');
    cfnIdMap[inst.InstanceId]=ln;
    const props={};
    if(inst.ImageId)props.ImageId=inst.ImageId;
    if(inst.InstanceType)props.InstanceType=inst.InstanceType;
    if(inst.SubnetId)props.SubnetId=cfnRef(inst.SubnetId);
    if(inst.KeyName)props.KeyName=inst.KeyName;
    const sgIds=(inst.SecurityGroups||inst.NetworkInterfaces&&inst.NetworkInterfaces[0]&&inst.NetworkInterfaces[0].Groups||[]).map(g=>g.GroupId).filter(Boolean);
    if(sgIds.length)props.SecurityGroupIds=sgIds.map(s=>cfnRef(s));
    props.Tags=_cfnTags(inst);
    template.Resources[ln]={Type:'AWS::EC2::Instance',Properties:props};
  });

  // ALBs
  albs.forEach(alb=>{
    const ln=cfnName(alb,'ALB');
    cfnIdMap[alb.LoadBalancerArn]=ln;
    const props={Type:alb.Type||'application',Scheme:alb.Scheme||'internet-facing'};
    if(alb.LoadBalancerName)props.Name=alb.LoadBalancerName;
    const albSubs=(alb.AvailabilityZones||[]).map(az=>az.SubnetId).filter(Boolean);
    if(albSubs.length)props.Subnets=albSubs.map(s=>cfnRef(s));
    const albSgs=(alb.SecurityGroups||[]);
    if(albSgs.length)props.SecurityGroups=albSgs.map(s=>cfnRef(s));
    template.Resources[ln]={Type:'AWS::ElasticLoadBalancingV2::LoadBalancer',Properties:props};
  });

  // RDS
  rdsInstances.forEach(rds=>{
    const ln=cfnName({Tags:[{Key:'Name',Value:rds.DBInstanceIdentifier}]},'RDS');
    cfnIdMap[rds.DBInstanceIdentifier]=ln;
    const props={DBInstanceIdentifier:rds.DBInstanceIdentifier};
    if(rds.Engine)props.Engine=rds.Engine;
    if(rds.EngineVersion)props.EngineVersion=rds.EngineVersion;
    if(rds.DBInstanceClass)props.DBInstanceClass=rds.DBInstanceClass;
    if(rds.AllocatedStorage)props.AllocatedStorage=String(rds.AllocatedStorage);
    if(rds.MultiAZ)props.MultiAZ=true;
    props.MasterUsername='admin';
    props.MasterUserPassword='CHANGE_ME';
    template.Resources[ln]={Type:'AWS::RDS::DBInstance',Properties:props};
  });

  // Outputs
  vpcs.forEach(vpc=>{
    const ln=cfnIdMap[vpc.VpcId];
    if(ln){
      template.Outputs[ln+'Id']={Value:{'Ref':ln},Description:'VPC ID for '+ln};
    }
  });

  // Serialize
  const format=opts.format||'yaml';
  let code;
  if(format==='json'){
    code=JSON.stringify(template,null,2);
  }else{
    code=_serializeCfnYaml(template);
  }

  if(sgCycles.length)warnings.push(sgCycles.length+' circular SG reference(s) detected. Rules split into standalone resources.');

  return {code:code,warnings:warnings,stats:{resources:Object.keys(template.Resources).length}};
}

function _cfnTags(resource){
  return (resource.Tags||[]).filter(t=>!t.Key.startsWith('aws:')).map(t=>({Key:t.Key,Value:t.Value||''}));
}

function _cfnSGRule(rule){
  const r={IpProtocol:rule.IpProtocol||'-1'};
  if(rule.FromPort!=null)r.FromPort=rule.FromPort;
  if(rule.ToPort!=null)r.ToPort=rule.ToPort;
  const cidrs=(rule.IpRanges||[]).map(c=>c.CidrIp).filter(Boolean);
  if(cidrs.length)r.CidrIp=cidrs[0]; // CFN inline rule takes single CIDR
  const sgRefs=(rule.UserIdGroupPairs||[]).map(p=>p.GroupId).filter(Boolean);
  if(sgRefs.length)r.SourceSecurityGroupId=sgRefs[0];
  return r;
}

function _cfnSGRuleProps(rule){
  const r={};
  if(rule.FromPort!=null)r.FromPort=rule.FromPort;
  if(rule.ToPort!=null)r.ToPort=rule.ToPort;
  const cidrs=(rule.IpRanges||[]).map(c=>c.CidrIp).filter(Boolean);
  if(cidrs.length)r.CidrIp=cidrs[0];
  const sgRefs=(rule.UserIdGroupPairs||[]).map(p=>p.GroupId).filter(Boolean);
  if(sgRefs.length)r.SourceSecurityGroupId=sgRefs[0];
  return r;
}

// === CHECKOV CFN GENERATOR ===
// Generates a security-property-rich CloudFormation template for Checkov scanning
function _ckId(name,prefix,seen){
  var base=(name||prefix||'Res').replace(/[^a-zA-Z0-9]/g,'');
  if(!base||/^\d/.test(base)) base=(prefix||'R')+base;
  var id=base,i=2;
  while(seen.has(id)){id=base+i;i++;}
  seen.add(id);
  return id;
}
function _ckVpcs(vpcs,res,seen){
  vpcs.forEach(function(v){
    var id=_ckId(gn(v,v.VpcId),'VPC',seen);
    res[id]={Type:'AWS::EC2::VPC',Properties:{
      CidrBlock:v.CidrBlock||'10.0.0.0/16',
      EnableDnsSupport:v.EnableDnsSupport!==false,
      EnableDnsHostnames:v.EnableDnsHostnames===true,
      Tags:_cfnTags(v)
    }};
  });
}
function _ckSubnets(subnets,res,seen){
  subnets.forEach(function(s){
    var id=_ckId(gn(s,s.SubnetId),'Subnet',seen);
    res[id]={Type:'AWS::EC2::Subnet',Properties:{
      VpcId:s.VpcId,CidrBlock:s.CidrBlock,
      AvailabilityZone:s.AvailabilityZone||'',
      MapPublicIpOnLaunch:s.MapPublicIpOnLaunch===true,
      Tags:_cfnTags(s)
    }};
  });
}
function _ckExpandRules(perms){
  var rules=[];
  (perms||[]).forEach(function(p){
    var base={IpProtocol:p.IpProtocol||'-1'};
    if(p.FromPort!=null) base.FromPort=p.FromPort;
    if(p.ToPort!=null) base.ToPort=p.ToPort;
    (p.IpRanges||[]).forEach(function(r){rules.push(Object.assign({},base,{CidrIp:r.CidrIp}));});
    (p.Ipv6Ranges||[]).forEach(function(r){rules.push(Object.assign({},base,{CidrIpv6:r.CidrIpv6}));});
    (p.UserIdGroupPairs||[]).forEach(function(pair){rules.push(Object.assign({},base,{SourceSecurityGroupId:pair.GroupId}));});
    if(!(p.IpRanges||[]).length&&!(p.Ipv6Ranges||[]).length&&!(p.UserIdGroupPairs||[]).length) rules.push(base);
  });
  return rules;
}
function _ckSgs(sgs,res,seen){
  sgs.forEach(function(sg){
    var id=_ckId(sg.GroupName||sg.GroupId,'SG',seen);
    res[id]={Type:'AWS::EC2::SecurityGroup',Properties:{
      GroupDescription:sg.Description||sg.GroupName||'',
      VpcId:sg.VpcId,
      SecurityGroupIngress:_ckExpandRules(sg.IpPermissions),
      SecurityGroupEgress:_ckExpandRules(sg.IpPermissionsEgress),
      Tags:_cfnTags(sg)
    }};
  });
}
function _ckNacls(nacls,res,seen){
  nacls.forEach(function(nacl){
    var nId=_ckId(gn(nacl,nacl.NetworkAclId),'NACL',seen);
    res[nId]={Type:'AWS::EC2::NetworkAcl',Properties:{VpcId:nacl.VpcId,Tags:_cfnTags(nacl)}};
    (nacl.Entries||[]).forEach(function(e){
      var eId=_ckId(nId+'Rule'+e.RuleNumber+(e.Egress?'E':'I'),'NACLEntry',seen);
      var props={NetworkAclId:nacl.NetworkAclId,RuleNumber:e.RuleNumber,
        Protocol:String(e.Protocol),RuleAction:e.RuleAction,Egress:e.Egress===true};
      if(e.CidrBlock) props.CidrBlock=e.CidrBlock;
      if(e.Ipv6CidrBlock) props.Ipv6CidrBlock=e.Ipv6CidrBlock;
      if(e.PortRange) props.PortRange={From:e.PortRange.From,To:e.PortRange.To};
      res[eId]={Type:'AWS::EC2::NetworkAclEntry',Properties:props};
    });
  });
}
function _ckRts(rts,res,seen){
  rts.forEach(function(rt){
    var rtId=_ckId(gn(rt,rt.RouteTableId),'RT',seen);
    res[rtId]={Type:'AWS::EC2::RouteTable',Properties:{VpcId:rt.VpcId,Tags:_cfnTags(rt)}};
    (rt.Routes||[]).forEach(function(r){
      if(r.GatewayId==='local') return;
      var rId=_ckId(rtId+(r.DestinationCidrBlock||'').replace(/[^a-zA-Z0-9]/g,''),'Route',seen);
      var props={RouteTableId:rt.RouteTableId};
      if(r.DestinationCidrBlock) props.DestinationCidrBlock=r.DestinationCidrBlock;
      if(r.GatewayId) props.GatewayId=r.GatewayId;
      if(r.NatGatewayId) props.NatGatewayId=r.NatGatewayId;
      if(r.VpcEndpointId) props.VpcEndpointId=r.VpcEndpointId;
      res[rId]={Type:'AWS::EC2::Route',Properties:props};
    });
  });
}
function _ckEc2(instances,ctx,res,seen){
  instances.forEach(function(inst){
    var id=_ckId(gn(inst,inst.InstanceId),'EC2',seen);
    var props={InstanceType:inst.InstanceType||'t3.micro',SubnetId:inst.SubnetId||'',
      SecurityGroupIds:(inst.SecurityGroups||[]).map(function(s){return s.GroupId}),
      ImageId:inst.ImageId||'',Tags:_cfnTags(inst)};
    // IMDSv2 — Checkov CKV_AWS_79
    var mo=inst.MetadataOptions||{};
    props.MetadataOptions={HttpTokens:mo.HttpTokens||'optional',HttpEndpoint:mo.HttpEndpoint||'enabled'};
    // IAM profile
    if(inst.IamInstanceProfile) props.IamInstanceProfile=inst.IamInstanceProfile.Arn||'';
    // EBS encryption
    if(inst.BlockDeviceMappings&&inst.BlockDeviceMappings.length){
      props.BlockDeviceMappings=inst.BlockDeviceMappings.map(function(b){
        var r={DeviceName:b.DeviceName||'/dev/xvda'};
        if(b.Ebs) r.Ebs={Encrypted:b.Ebs.Encrypted===true,VolumeSize:b.Ebs.VolumeSize||8,VolumeType:b.Ebs.VolumeType||'gp3'};
        return r;
      });
    }
    res[id]={Type:'AWS::EC2::Instance',Properties:props};
  });
}
function _ckRds(rdsInstances,res,seen){
  rdsInstances.forEach(function(db){
    var id=_ckId(db.DBInstanceIdentifier,'RDS',seen);
    res[id]={Type:'AWS::RDS::DBInstance',Properties:{
      DBInstanceIdentifier:db.DBInstanceIdentifier,
      Engine:db.Engine||'',EngineVersion:db.EngineVersion||'',
      DBInstanceClass:db.DBInstanceClass||'db.t3.micro',
      StorageEncrypted:db.StorageEncrypted===true,
      PubliclyAccessible:db.PubliclyAccessible===true,
      MultiAZ:db.MultiAZ===true,
      BackupRetentionPeriod:db.BackupRetentionPeriod||0,
      StorageType:db.StorageType||'gp2',
      AllocatedStorage:db.AllocatedStorage||20,
      MasterUsername:'admin'
    }};
  });
}
function _ckS3(buckets,res,seen){
  buckets.forEach(function(bk){
    var id=_ckId(bk.Name,'S3',seen);
    var props={BucketName:bk.Name};
    // Omit encryption/versioning — Checkov flags their absence, which is correct
    if(bk.BucketEncryption) props.BucketEncryption=bk.BucketEncryption;
    if(bk.VersioningConfiguration) props.VersioningConfiguration=bk.VersioningConfiguration;
    res[id]={Type:'AWS::S3::Bucket',Properties:props};
  });
}
function _ckAlbs(albs,res,seen){
  albs.forEach(function(alb){
    var id=_ckId(alb.LoadBalancerName||alb.LoadBalancerArn,'ALB',seen);
    var props={Type:alb.Type||'application',Scheme:alb.Scheme||'internet-facing'};
    if(alb.SecurityGroups) props.SecurityGroups=alb.SecurityGroups;
    if(alb.Subnets) props.Subnets=alb.Subnets;
    else if(alb.AvailabilityZones) props.Subnets=alb.AvailabilityZones.map(function(az){return az.SubnetId}).filter(Boolean);
    res[id]={Type:'AWS::ElasticLoadBalancingV2::LoadBalancer',Properties:props};
  });
}
function _ckLambda(fns,res,seen){
  fns.forEach(function(fn){
    var id=_ckId(fn.FunctionName,'Lambda',seen);
    var props={FunctionName:fn.FunctionName,Runtime:fn.Runtime||'',Handler:fn.Handler||'index.handler',
      MemorySize:fn.MemorySize||128,Timeout:fn.Timeout||3,
      Role:fn.Role||'arn:aws:iam::111222333444:role/LambdaRole',
      Code:{ZipFile:'exports.handler=async()=>({})'}};
    if(fn.VpcConfig&&fn.VpcConfig.SubnetIds&&fn.VpcConfig.SubnetIds.length){
      props.VpcConfig={SubnetIds:fn.VpcConfig.SubnetIds,SecurityGroupIds:fn.VpcConfig.SecurityGroupIds||[]};
    }
    res[id]={Type:'AWS::Lambda::Function',Properties:props};
  });
}
function _ckIamRoles(roles,res,seen){
  roles.forEach(function(role){
    var id=_ckId(role.RoleName,'Role',seen);
    var props={RoleName:role.RoleName,
      AssumeRolePolicyDocument:role.AssumeRolePolicyDocument||{Version:'2012-10-17',Statement:[]}};
    var managed=(role.AttachedManagedPolicies||[]).map(function(p){return p.PolicyArn}).filter(Boolean);
    if(managed.length) props.ManagedPolicyArns=managed;
    if(role.RolePolicyList&&role.RolePolicyList.length){
      props.Policies=role.RolePolicyList.map(function(p){
        return {PolicyName:p.PolicyName,PolicyDocument:p.PolicyDocument||{}};
      });
    }
    res[id]={Type:'AWS::IAM::Role',Properties:props};
  });
}
function _ckIamUsers(users,res,seen){
  users.forEach(function(user){
    var id=_ckId(user.UserName,'User',seen);
    var props={UserName:user.UserName};
    var managed=(user.AttachedManagedPolicies||[]).map(function(p){return p.PolicyArn}).filter(Boolean);
    if(managed.length) props.ManagedPolicyArns=managed;
    if(user.UserPolicyList&&user.UserPolicyList.length){
      props.Policies=user.UserPolicyList.map(function(p){
        return {PolicyName:p.PolicyName,PolicyDocument:p.PolicyDocument||{}};
      });
    }
    res[id]={Type:'AWS::IAM::User',Properties:props};
  });
}
function _ckElastiCache(clusters,res,seen){
  clusters.forEach(function(c){
    var id=_ckId(c.CacheClusterId,'Cache',seen);
    res[id]={Type:'AWS::ElastiCache::CacheCluster',Properties:{
      Engine:c.Engine||'redis',CacheNodeType:c.CacheNodeType||'cache.t3.micro',
      NumCacheNodes:c.NumCacheNodes||1,
      AtRestEncryptionEnabled:c.AtRestEncryptionEnabled===true,
      TransitEncryptionEnabled:c.TransitEncryptionEnabled===true
    }};
  });
}
function _ckRedshift(clusters,res,seen){
  clusters.forEach(function(c){
    var id=_ckId(c.ClusterIdentifier,'Redshift',seen);
    res[id]={Type:'AWS::Redshift::Cluster',Properties:{
      ClusterIdentifier:c.ClusterIdentifier,
      NodeType:c.NodeType||'dc2.large',NumberOfNodes:c.NumberOfNodes||1,
      Encrypted:c.Encrypted===true,PubliclyAccessible:c.PubliclyAccessible===true,
      MasterUsername:'admin',MasterUserPassword:'placeholder',
      DBName:c.DBName||'dev'
    }};
  });
}
function generateCheckovCfn(ctx,iamData){
  if(!ctx||!ctx.vpcs) return null;
  var template={AWSTemplateFormatVersion:'2010-09-09',
    Description:'Generated by AWS Mapper for Checkov scanning — '+new Date().toISOString().split('T')[0],
    Resources:{}};
  var res=template.Resources,seen=new Set();
  _ckVpcs(ctx.vpcs||[],res,seen);
  _ckSubnets(ctx.subnets||[],res,seen);
  _ckSgs(ctx.sgs||[],res,seen);
  _ckNacls(ctx.nacls||[],res,seen);
  _ckRts(ctx.rts||[],res,seen);
  _ckEc2(ctx.instances||[],ctx,res,seen);
  _ckRds(ctx.rdsInstances||[],res,seen);
  _ckS3(ctx.s3bk||[],res,seen);
  _ckAlbs(ctx.albs||[],res,seen);
  _ckLambda(ctx.lambdaFns||[],res,seen);
  _ckElastiCache(ctx.ecacheClusters||[],res,seen);
  _ckRedshift(ctx.redshiftClusters||[],res,seen);
  if(iamData){
    _ckIamRoles(iamData.roles||[],res,seen);
    _ckIamUsers(iamData.users||[],res,seen);
  }
  return JSON.stringify(template,null,2);
}

// --- Simple YAML serializer for CFN ---
function _serializeCfnYaml(obj,indent){
  indent=indent||0;
  const pad='  '.repeat(indent);
  const lines=[];
  if(obj===null||obj===undefined)return 'null';
  if(typeof obj==='boolean')return obj?'true':'false';
  if(typeof obj==='number')return String(obj);
  if(typeof obj==='string'){
    if(obj.includes('\n'))return '|\n'+obj.split('\n').map(l=>pad+'  '+l).join('\n');
    if(obj.match(/[:{}\[\],&*?|>!%@`#'"]/)||obj===''||obj==='true'||obj==='false'||!isNaN(obj))return "'"+obj.replace(/'/g,"''")+"'";
    return obj;
  }
  if(Array.isArray(obj)){
    if(obj.length===0)return '[]';
    // Check if array of simple values
    if(obj.every(v=>typeof v==='string'||typeof v==='number'||typeof v==='boolean')){
      return '['+obj.map(v=>{
        if(typeof v==='string')return "'"+v.replace(/'/g,"''")+"'";
        return String(v);
      }).join(', ')+']';
    }
    obj.forEach(item=>{
      if(typeof item==='object'&&item!==null&&!Array.isArray(item)){
        const keys=Object.keys(item);
        if(keys.length){
          lines.push(pad+'- '+keys[0]+': '+_serializeCfnYaml(item[keys[0]],indent+2));
          keys.slice(1).forEach(k=>{
            lines.push(pad+'  '+k+': '+_serializeCfnYaml(item[k],indent+2));
          });
        }else{
          lines.push(pad+'- {}');
        }
      }else{
        lines.push(pad+'- '+_serializeCfnYaml(item,indent+1));
      }
    });
    return '\n'+lines.join('\n');
  }
  if(typeof obj==='object'){
    // Handle CFN intrinsic functions
    const keys=Object.keys(obj);
    if(keys.length===1&&keys[0]==='Ref')return '!Ref '+obj.Ref;
    if(keys.length===1&&keys[0]==='Fn::GetAtt')return '!GetAtt '+obj['Fn::GetAtt'].join('.');
    if(keys.length===1&&keys[0]==='Fn::Sub')return '!Sub '+_serializeCfnYaml(obj['Fn::Sub'],indent);

    if(keys.length===0)return '{}';
    keys.forEach(k=>{
      const val=obj[k];
      if(val===null||val===undefined)return;
      if(typeof val==='object'&&!Array.isArray(val)&&Object.keys(val).length>0){
        // Check for intrinsic
        const vkeys=Object.keys(val);
        if(vkeys.length===1&&vkeys[0]==='Ref'){
          lines.push(pad+k+': !Ref '+val.Ref);
        }else if(vkeys.length===1&&vkeys[0]==='Fn::GetAtt'){
          lines.push(pad+k+': !GetAtt '+val['Fn::GetAtt'].join('.'));
        }else{
          lines.push(pad+k+':');
          lines.push(_serializeCfnYaml(val,indent+1));
        }
      }else if(Array.isArray(val)){
        const ser=_serializeCfnYaml(val,indent+1);
        if(ser.startsWith('\n')){
          lines.push(pad+k+':'+ser);
        }else{
          lines.push(pad+k+': '+ser);
        }
      }else{
        lines.push(pad+k+': '+_serializeCfnYaml(val,indent+1));
      }
    });
    return lines.join('\n');
  }
  return String(obj);
}

// --- Syntax Highlighting (basic HCL) ---
function _highlightHCL(code){
  // Escape HTML first
  code=code.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  // Process line-by-line to avoid cross-match issues
  return code.split('\n').map(line=>{
    // Comments take precedence
    if(line.match(/^\s*#/))return '<span class="hcl-cmt">'+line+'</span>';
    // Strings: replace "..." with colored spans
    line=line.replace(/"([^"]*)"/g,function(_,s){return '"<span class="hcl-str">'+s+'</span>"'});
    // Keywords
    line=line.replace(/\b(resource|variable|data|module|provider|output|terraform|required_providers|import|locals|dynamic)\b/g,'<span class="hcl-kw">$1</span>');
    // Types
    line=line.replace(/\b(string|number|bool|list|map|set|object|any)\b/g,'<span class="hcl-type">$1</span>');
    // Numbers (standalone, not inside strings)
    line=line.replace(/= (\d+)$/g,'= <span class="hcl-num">$1</span>');
    // Booleans
    line=line.replace(/\b(true|false|null)\b/g,'<span class="hcl-num">$1</span>');
    // Resource refs
    line=line.replace(/(aws_[a-z_]+\.[a-z_0-9]+\.[a-z_]+)/g,'<span class="hcl-ref">$1</span>');
    return line;
  }).join('\n');
}

function _highlightYAML(code){
  code=code.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  return code.split('\n').map(line=>{
    if(line.match(/^\s*#/))return '<span class="hcl-cmt">'+line+'</span>';
    line=line.replace(/(!Ref|!GetAtt|!Sub|!Select|!Join|!If)\b/g,'<span class="hcl-kw">$1</span>');
    line=line.replace(/(AWS::[A-Za-z0-9:]+)/g,'<span class="hcl-type">$1</span>');
    line=line.replace(/'([^']*)'/g,"'<span class=\"hcl-str\">$1</span>'");
    line=line.replace(/\b(true|false|null)\b/g,'<span class="hcl-num">$1</span>');
    return line;
  }).join('\n');
}

export {
  _sanitizeName, _tfName, _tfRef, detectCircularSGs,
  generateTerraform, generateCloudFormation,
  _cfnTags, _cfnSGRule, _cfnSGRuleProps,
  generateCheckovCfn, _serializeCfnYaml,
  _highlightHCL, _highlightYAML,
  _ckId, _ckVpcs, _ckSubnets, _ckSgs, _ckNacls, _ckRts,
  _ckEc2, _ckRds, _ckS3, _ckAlbs, _ckLambda, _ckElastiCache, _ckRedshift,
  _ckExpandRules, _ckIamRoles, _ckIamUsers
};
