/**
 * Export Script Generators — Bash and PowerShell data export scripts
 * Extracted from app-core.js
 * Returns script string content for download.
 */

export function generateBashScript() {
  var script=[
  '#!/usr/bin/env bash',
  '# AWS Network Mapper — Data Export Script',
  '# Usage:',
  '#   ./export-aws-data.sh                                 # default profile + region',
  '#   ./export-aws-data.sh -p prod -r us-west-2',
  '#   ./export-aws-data.sh -p prod -a                      # all regions, skip empty',
  '#   ./export-aws-data.sh -P prod,staging,dev -a           # multi-profile, all regions',
  '#   ./export-aws-data.sh -p prod -r us-east-1 -o ./out',
  'set -euo pipefail',
  'PROFILE="";REGION="";OUTDIR="";ALL_REGIONS=false;PROFILES=""',
  'usage(){ echo "Usage: $0 [-p profile] [-r region] [-o dir] [-a all-regions] [-P profiles]"; exit 1; }',
  'while getopts "p:r:o:P:ah" opt; do case $opt in p) PROFILE="$OPTARG";; r) REGION="$OPTARG";; o) OUTDIR="$OPTARG";; P) PROFILES="$OPTARG";; a) ALL_REGIONS=true;; *) usage;; esac; done',
  '[[ -n "$PROFILE" && ! "$PROFILE" =~ ^[a-zA-Z0-9_-]+$ ]] && echo "ERROR: Invalid profile" >&2 && exit 1',
  '[[ -n "$REGION" && ! "$REGION" =~ ^[a-zA-Z0-9-]+$ ]] && echo "ERROR: Invalid region" >&2 && exit 1',
  'command -v aws &>/dev/null || { echo "ERROR: AWS CLI not found" >&2; exit 1; }',
  '_has_data(){ python3 -c "import json,sys;d=json.load(sys.stdin);sys.exit(0 if any(isinstance(v,list) and len(v)>0 for v in d.values()) else 1)" 2>/dev/null; }',
  'AWS_FLAGS=();CUR_OUT=""',
  'run(){ local label="$1" fn="$2"; shift 2; printf "  %-35s" "$label..."; if output=$(aws "${AWS_FLAGS[@]}" "$@" 2>&1); then if printf \'%s\' "$output" | _has_data; then echo "$output" > "$CUR_OUT/$fn"; echo "OK ($(wc -c < "$CUR_OUT/$fn" | tr -d \' \') bytes)"; else echo "SKIP (empty)"; fi; else echo "SKIP"; fi; }',
  'has_resources(){ local r; r=$(aws "${AWS_FLAGS[@]}" ec2 describe-vpcs --query \'Vpcs[?IsDefault==`false`].VpcId\' --output json 2>/dev/null) || return 1; [ "$(printf \'%s\' "$r" | python3 -c \'import json,sys;print(len(json.load(sys.stdin)))\' 2>/dev/null)" != "0" ]; }',
  'export_all(){',
  'mkdir -p "$CUR_OUT"',
  'echo "── Network ─────────────────────────────────"',
  'run "VPCs"                    "vpcs.json"                    ec2 describe-vpcs',
  'run "Subnets"                 "subnets.json"                 ec2 describe-subnets',
  'run "Route Tables"            "route-tables.json"            ec2 describe-route-tables',
  'run "Security Groups"         "security-groups.json"         ec2 describe-security-groups',
  'run "Network ACLs"            "network-acls.json"            ec2 describe-network-acls',
  'run "ENIs"                    "network-interfaces.json"      ec2 describe-network-interfaces',
  '',
  'echo "── Gateways ────────────────────────────────"',
  'run "Internet Gateways"       "internet-gateways.json"       ec2 describe-internet-gateways',
  'run "NAT Gateways"            "nat-gateways.json"            ec2 describe-nat-gateways',
  'run "VPC Endpoints"           "vpc-endpoints.json"           ec2 describe-vpc-endpoints',
  '',
  'echo "── Compute ─────────────────────────────────"',
  'run "EC2 Instances"           "ec2-instances.json"           ec2 describe-instances',
  'run "RDS Instances"           "rds-instances.json"           rds describe-db-instances',
  'run "Lambda Functions"        "lambda-functions.json"        lambda list-functions',
  'run "ElastiCache Clusters"    "elasticache-clusters.json"    elasticache describe-cache-clusters --show-cache-node-info',
  'run "Redshift Clusters"       "redshift-clusters.json"       redshift describe-clusters',
  '',
  'echo "── Load Balancing ──────────────────────────"',
  'run "ALBs / NLBs"             "load-balancers.json"          elbv2 describe-load-balancers',
  'run "Target Groups"           "target-groups.json"           elbv2 describe-target-groups',
  '',
  'echo "── Connectivity ────────────────────────────"',
  'run "VPC Peering"             "vpc-peering.json"             ec2 describe-vpc-peering-connections',
  'run "VPN Connections"         "vpn-connections.json"         ec2 describe-vpn-connections',
  'run "TGW Attachments"         "tgw-attachments.json"         ec2 describe-transit-gateway-attachments',
  '',
  'echo "── Storage ──────────────────────────────────"',
  'run "EBS Volumes"             "volumes.json"                 ec2 describe-volumes',
  'run "EBS Snapshots"           "snapshots.json"               ec2 describe-snapshots --owner-ids self',
  'run "S3 Buckets"              "s3-buckets.json"              s3api list-buckets',
  '',
  'echo "── DNS ─────────────────────────────────────"',
  'run "Route 53 Hosted Zones"   "hosted-zones.json"            route53 list-hosted-zones',
  '',
  'echo "── Security ────────────────────────────────"',
  'run "WAF WebACLs"             "waf-web-acls.json"            wafv2 list-web-acls --scope REGIONAL',
  'run "CloudFront Distributions" "cloudfront.json"             cloudfront list-distributions',
  '',
  'echo "── IAM ─────────────────────────────────────"',
  'run "IAM Authorization"       "iam.json"                     iam get-account-authorization-details',
  '',
  'echo "── Multi-step ─────────────────────────────"',
  'if [ -f "$CUR_OUT/hosted-zones.json" ]; then',
  '  printf "  %-35s" "Route 53 Records..."',
  '  zones=$(python3 -c "import json;[print(z[\'Id\'].split(\'/\')[-1]) for z in json.load(open(\'$CUR_OUT/hosted-zones.json\')).get(\'HostedZones\',[])]" 2>/dev/null || true)',
  '  echo \'{"RecordSets":[]}\' > "$CUR_OUT/r53-records.json"',
  '  for zid in $zones; do',
  '    [[ ! "$zid" =~ ^[A-Z0-9]+$ ]] && continue',
  '    if rr=$(aws "${AWS_FLAGS[@]}" route53 list-resource-record-sets --hosted-zone-id "$zid" 2>/dev/null); then',
  '      printf \'%s\' "$rr" > "$CUR_OUT/_tmp_r53.json"',
  '      python3 -c "import json;a=json.load(open(\'$CUR_OUT/r53-records.json\'));b=json.load(open(\'$CUR_OUT/_tmp_r53.json\'));a[\'RecordSets\'].extend(b.get(\'ResourceRecordSets\',[]));json.dump(a,open(\'$CUR_OUT/r53-records.json\',\'w\'))" 2>/dev/null',
  '    fi',
  '  done',
  '  rm -f "$CUR_OUT/_tmp_r53.json"',
  '  count=$(python3 -c "import json;print(len(json.load(open(\'$CUR_OUT/r53-records.json\')).get(\'RecordSets\',[])))" 2>/dev/null || echo 0)',
  '  if [ "$count" = "0" ]; then rm -f "$CUR_OUT/r53-records.json"; echo "SKIP (empty)"; else echo "OK ($count records)"; fi',
  'fi',
  'printf "  %-35s" "ECS Services..."',
  'if clusters=$(aws "${AWS_FLAGS[@]}" ecs list-clusters --query \'clusterArns[]\' --output text 2>&1) && [ -n "$clusters" ] && [ "$clusters" != "None" ]; then',
  '  echo \'{"services":[]}\' > "$CUR_OUT/ecs-services.json"',
  '  for cluster in $clusters; do',
  '    [[ ! "$cluster" =~ ^arn:aws ]] && continue',
  '    svc_arns=$(aws "${AWS_FLAGS[@]}" ecs list-services --cluster "$cluster" --query \'serviceArns[]\' --output text 2>/dev/null || true)',
  '    if [ -n "$svc_arns" ] && [ "$svc_arns" != "None" ]; then',
  '      for svc_arn in $svc_arns; do',
  '        [[ ! "$svc_arn" =~ ^arn:aws ]] && continue',
  '        aws "${AWS_FLAGS[@]}" ecs describe-services --cluster "$cluster" --services "$svc_arn" > "$CUR_OUT/_tmp_ecs.json" 2>/dev/null && \\',
  '        python3 -c "import json,sys;a=json.load(open(sys.argv[1]));b=json.load(open(sys.argv[2]));a[\'services\'].extend(b.get(\'services\',[]));json.dump(a,open(sys.argv[1],\'w\'))" "$CUR_OUT/ecs-services.json" "$CUR_OUT/_tmp_ecs.json" 2>/dev/null',
  '      done',
  '    fi',
  '  done',
  '  rm -f "$CUR_OUT/_tmp_ecs.json"; echo "OK"',
  'else echo "SKIP (no clusters)"; fi',
  '}',
  '',
  'echo "AWS Network Mapper — Data Export"',
  'echo ""',
  'PROF_LIST=()',
  'if [[ -n "$PROFILES" ]]; then IFS=\',\' read -ra PROF_LIST <<< "$PROFILES"',
  'elif [[ -n "$PROFILE" ]]; then PROF_LIST=("$PROFILE"); fi',
  'if [[ ${#PROF_LIST[@]} -gt 0 ]]; then',
  '  [[ -z "$OUTDIR" ]] && OUTDIR="./aws-export-multi-$(date +%Y%m%d-%H%M%S)"',
  '  echo "  Profiles: ${PROF_LIST[*]}"',
  '  for prof in "${PROF_LIST[@]}"; do',
  '    prof=$(echo "$prof" | xargs)',
  '    echo ""; echo "=== Profile: $prof ==="',
  '    if $ALL_REGIONS; then',
  '      regions=$(aws --profile "$prof" ec2 describe-regions --query \'Regions[].RegionName\' --output text 2>/dev/null | tr \'\\t\' \'\\n\' | sort)',
  '      skip=0',
  '      for reg in $regions; do',
  '        AWS_FLAGS=(--profile "$prof" --region "$reg")',
  '        if ! has_resources; then skip=$((skip+1)); continue; fi',
  '        echo "  Region: $reg"; CUR_OUT="$OUTDIR/$prof/$reg"; export_all',
  '      done',
  '      [ $skip -gt 0 ] && echo "  Skipped $skip empty regions"',
  '    else',
  '      AWS_FLAGS=(--profile "$prof"); [[ -n "$REGION" ]] && AWS_FLAGS+=(--region "$REGION")',
  '      CUR_OUT="$OUTDIR/$prof"; export_all',
  '    fi',
  '  done',
  'elif $ALL_REGIONS; then',
  '  AWS_FLAGS=(); [[ -n "$PROFILE" ]] && AWS_FLAGS+=(--profile "$PROFILE")',
  '  [[ -z "$OUTDIR" ]] && OUTDIR="./aws-export-${PROFILE:-default}-allregions-$(date +%Y%m%d-%H%M%S)"',
  '  regions=$(aws "${AWS_FLAGS[@]}" ec2 describe-regions --query \'Regions[].RegionName\' --output text 2>/dev/null | tr \'\\t\' \'\\n\' | sort)',
  '  echo "  Mode: All Regions  Profile: ${PROFILE:-default}"; skip=0',
  '  for reg in $regions; do',
  '    AWS_FLAGS=(); [[ -n "$PROFILE" ]] && AWS_FLAGS+=(--profile "$PROFILE"); AWS_FLAGS+=(--region "$reg")',
  '    if ! has_resources; then echo "  $reg — empty, skipping"; skip=$((skip+1)); continue; fi',
  '    echo "  Region: $reg"; CUR_OUT="$OUTDIR/$reg"; export_all',
  '  done',
  '  [ $skip -gt 0 ] && echo "  Skipped $skip empty regions"',
  'else',
  '  AWS_FLAGS=(); [[ -n "$PROFILE" ]] && AWS_FLAGS+=(--profile "$PROFILE"); [[ -n "$REGION" ]] && AWS_FLAGS+=(--region "$REGION")',
  '  [[ -z "$OUTDIR" ]] && OUTDIR="./aws-export-${PROFILE:-default}-$(date +%Y%m%d-%H%M%S)"',
  '  echo "  Profile: ${PROFILE:-default}  Region: ${REGION:-default}  Output: $OUTDIR"',
  '  CUR_OUT="$OUTDIR"; export_all',
  'fi',
  'echo ""',
  'count=$(find "$OUTDIR" -name \'*.json\' 2>/dev/null | wc -l | tr -d \' \')',
  'size=$(du -sh "$OUTDIR" 2>/dev/null | cut -f1)',
  'echo "Done! $count files ($size) -> $OUTDIR"',
  'echo "Drag folder onto Upload JSON Files or paste individually."'
  ].join('\n');
  return script;
}

export function generatePsScript() {
  var script=[
  '#Requires -Version 7.0',
  '<#',
  '.SYNOPSIS',
  '    AWS Network Mapper - Data Export Script (PowerShell)',
  '.DESCRIPTION',
  '    Exports all AWS CLI data needed for the web-based mapper tool.',
  '    Supports multi-region sweep and parallel execution.',
  '.PARAMETER Profile',
  '    AWS CLI profile name (optional)',
  '.PARAMETER Region',
  '    AWS region (optional)',
  '.PARAMETER OutputDir',
  '    Output directory (optional)',
  '.PARAMETER AllRegions',
  '    Sweep all enabled regions into subfolders',
  '.PARAMETER MaxParallel',
  '    Max concurrent API calls (default: 6)',
  '.EXAMPLE',
  '    ./export-aws-data.ps1',
  '    ./export-aws-data.ps1 -Profile prod -Region us-west-2',
  '    ./export-aws-data.ps1 -Profile prod -AllRegions -MaxParallel 8',
  '    ./export-aws-data.ps1 -Profiles dev,staging,prod -AllRegions',
  '#>',
  '[CmdletBinding()]',
  'param([Alias("p")][string]$Profile,[Alias("r")][string]$Region,[Alias("o")][string]$OutputDir,[switch]$AllRegions,[string[]]$Profiles,[int]$MaxParallel=6)',
  '$ErrorActionPreference="Stop"',
  'if(-not $PSBoundParameters.ContainsKey(\'Profile\')){$Profile=$null}',
  'if($Profile -and $Profile -notmatch \'^[a-zA-Z0-9_-]+$\'){Write-Error "Invalid profile";exit 1}',
  'if($Region -and $Region -notmatch \'^[a-zA-Z0-9-]+$\'){Write-Error "Invalid region";exit 1}',
  'if(-not(Get-Command aws -ErrorAction SilentlyContinue)){Write-Error "AWS CLI not found";exit 1}',
  '$profileList=@()',
  'if($Profiles){$profileList=@($Profiles|ForEach-Object{$_ -split ","}|ForEach-Object{$_.Trim()}|Where-Object{$_})}',
  'if($Profile -and $profileList.Count -eq 0){$profileList=@($Profile)}',
  '$awsFlags=@(); if($Profile){$awsFlags+=@("--profile",$Profile)}',
  'function Get-BaseFlags([string]$reg){$f=@();if($Profile){$f+=@("--profile",$Profile)};if($reg){$f+=@("--region",$reg)};return $f}',
  '$exports=@(',
  '  @{Label="VPCs";File="vpcs.json";Cmd=@("ec2","describe-vpcs")},',
  '  @{Label="Subnets";File="subnets.json";Cmd=@("ec2","describe-subnets")},',
  '  @{Label="Route Tables";File="route-tables.json";Cmd=@("ec2","describe-route-tables")},',
  '  @{Label="Security Groups";File="security-groups.json";Cmd=@("ec2","describe-security-groups")},',
  '  @{Label="Network ACLs";File="network-acls.json";Cmd=@("ec2","describe-network-acls")},',
  '  @{Label="ENIs";File="network-interfaces.json";Cmd=@("ec2","describe-network-interfaces")},',
  '  @{Label="Internet GWs";File="internet-gateways.json";Cmd=@("ec2","describe-internet-gateways")},',
  '  @{Label="NAT GWs";File="nat-gateways.json";Cmd=@("ec2","describe-nat-gateways")},',
  '  @{Label="VPC Endpoints";File="vpc-endpoints.json";Cmd=@("ec2","describe-vpc-endpoints")},',
  '  @{Label="EC2 Instances";File="ec2-instances.json";Cmd=@("ec2","describe-instances")},',
  '  @{Label="RDS Instances";File="rds-instances.json";Cmd=@("rds","describe-db-instances")},',
  '  @{Label="Lambda Functions";File="lambda-functions.json";Cmd=@("lambda","list-functions")},',
  '  @{Label="ElastiCache";File="elasticache-clusters.json";Cmd=@("elasticache","describe-cache-clusters","--show-cache-node-info")},',
  '  @{Label="Redshift";File="redshift-clusters.json";Cmd=@("redshift","describe-clusters")},',
  '  @{Label="ALBs/NLBs";File="load-balancers.json";Cmd=@("elbv2","describe-load-balancers")},',
  '  @{Label="Target Groups";File="target-groups.json";Cmd=@("elbv2","describe-target-groups")},',
  '  @{Label="VPC Peering";File="vpc-peering.json";Cmd=@("ec2","describe-vpc-peering-connections")},',
  '  @{Label="VPN Connections";File="vpn-connections.json";Cmd=@("ec2","describe-vpn-connections")},',
  '  @{Label="TGW Attachments";File="tgw-attachments.json";Cmd=@("ec2","describe-transit-gateway-attachments")},',
  '  @{Label="EBS Volumes";File="volumes.json";Cmd=@("ec2","describe-volumes")},',
  '  @{Label="EBS Snapshots";File="snapshots.json";Cmd=@("ec2","describe-snapshots","--owner-ids","self")},',
  '  @{Label="S3 Buckets";File="s3-buckets.json";Cmd=@("s3api","list-buckets")},',
  '  @{Label="Route 53 Zones";File="hosted-zones.json";Cmd=@("route53","list-hosted-zones")},',
  '  @{Label="WAF WebACLs";File="waf-web-acls.json";Cmd=@("wafv2","list-web-acls","--scope","REGIONAL")},',
  '  @{Label="CloudFront";File="cloudfront.json";Cmd=@("cloudfront","list-distributions")},',
  '  @{Label="IAM Auth";File="iam.json";Cmd=@("iam","get-account-authorization-details")}',
  ')',
  'function Export-EcsServices{param([string[]]$Flags,[string]$OutPath)',
  '  Write-Host "    ECS Services..." -NoNewline',
  '  try{$raw=& aws @Flags ecs list-clusters --query \'clusterArns[]\' --output json 2>&1',
  '    if($LASTEXITCODE -ne 0 -or -not $raw){Write-Host " SKIP" -ForegroundColor Yellow;return}',
  '    $clusters=$raw|ConvertFrom-Json;$allSvcs=@()',
  '    foreach($c in $clusters){if($c -notmatch \'^arn:aws\'){continue}',
  '      $sa=& aws @Flags ecs list-services --cluster $c --query \'serviceArns[]\' --output json 2>$null',
  '      if($LASTEXITCODE -ne 0 -or -not $sa){continue};$svcArns=$sa|ConvertFrom-Json',
  '      foreach($s in $svcArns){if($s -notmatch \'^arn:aws\'){continue}',
  '        $d=& aws @Flags ecs describe-services --cluster $c --services $s 2>$null',
  '        if($LASTEXITCODE -eq 0 -and $d){$allSvcs+=($d|ConvertFrom-Json).services}}}',
  '    @{services=$allSvcs}|ConvertTo-Json -Depth 10|Out-File(Join-Path $OutPath "ecs-services.json")-Encoding utf8',
  '    Write-Host " OK ($($allSvcs.Count))" -ForegroundColor Green',
  '  }catch{Write-Host " SKIP" -ForegroundColor Yellow}}',
  'function Export-R53Records{param([string[]]$Flags,[string]$OutPath)',
  '  $zf=Join-Path $OutPath "hosted-zones.json";if(-not(Test-Path $zf)){return}',
  '  $zones=(Get-Content $zf -Raw|ConvertFrom-Json).HostedZones;if(-not $zones -or $zones.Count -eq 0){return}',
  '  $all=@();foreach($z in $zones){$zid=$z.Id -replace "/hostedzone/","";if($zid -notmatch "^[A-Z0-9]+$"){continue}',
  '    Write-Host "    R53 ($zid)..." -NoNewline',
  '    try{$raw=& aws @Flags route53 list-resource-record-sets --hosted-zone-id $zid 2>&1',
  '      if($LASTEXITCODE -eq 0){$d=$raw|ConvertFrom-Json;$all+=$d.ResourceRecordSets;Write-Host " OK" -ForegroundColor Green}',
  '      else{Write-Host " SKIP" -ForegroundColor Yellow}}catch{Write-Host " SKIP" -ForegroundColor Yellow}}',
  '  if($all.Count -gt 0){@{RecordSets=$all}|ConvertTo-Json -Depth 10|Out-File(Join-Path $OutPath "r53-records.json")-Encoding utf8}}',
  'function Export-Region{param([string]$RegionName,[string]$OutPath,[int]$Parallel)',
  '  $flags=Get-BaseFlags $RegionName;New-Item -ItemType Directory -Path $OutPath -Force|Out-Null',
  '  $results=$exports|ForEach-Object -ThrottleLimit $Parallel -Parallel{',
  '    $fp=Join-Path $using:OutPath $_.File',
  '    try{$r=& aws @using:flags @($_.Cmd) 2>&1',
  '      if($LASTEXITCODE -eq 0){$j=($r|Out-String)|ConvertFrom-Json;$hd=$false;foreach($p in $j.PSObject.Properties){if($p.Value -is [System.Array] -and $p.Value.Count -gt 0){$hd=$true;break}};if($hd){$r|Out-File -FilePath $fp -Encoding utf8;$sz=(Get-Item $fp).Length;@{L=$_.Label;S="OK";D="${sz} bytes"}}else{@{L=$_.Label;S="SKIP";D="empty"}}}',
  '      else{$m=($r|Out-String).Trim();if($m.Length -gt 60){$m=$m.Substring(0,60)};@{L=$_.Label;S="SKIP";D=$m}}}',
  '    catch{@{L=$_.Label;S="SKIP";D=$_.Exception.Message.Substring(0,[Math]::Min(60,$_.Exception.Message.Length))}}}',
  '  foreach($r in $results){$c=if($r.S -eq "OK"){"Green"}else{"Yellow"};Write-Host("  {0,-30} {1} ({2})" -f $r.L,$r.S,$r.D)-ForegroundColor $c}',
  '  Export-EcsServices -Flags $flags -OutPath $OutPath',
  '  Export-R53Records -Flags $flags -OutPath $OutPath}',
  'Write-Host "`n  AWS Network Mapper - Data Export (PowerShell)`n" -ForegroundColor Magenta',
  'function Test-HasResources([string[]]$f){try{$r=& aws @f ec2 describe-vpcs --query \'Vpcs[?IsDefault==`false`].VpcId\' --output json 2>&1;if($LASTEXITCODE -ne 0){return $false};$v=$r|ConvertFrom-Json;return($v.Count -gt 0)}catch{return $false}}',
  'if($Profiles){',
  '  if(-not $OutputDir){$ts=Get-Date -Format "yyyyMMdd-HHmmss";$OutputDir="./aws-export-multi-${ts}"}',
  '  New-Item -ItemType Directory -Path $OutputDir -Force|Out-Null',
  '  Write-Host "  Profiles: $($profileList -join \', \')`n" -ForegroundColor Cyan',
  '  foreach($prof in $profileList){',
  '    $Profile=$prof;$awsFlags=@("--profile",$prof)',
  '    Write-Host "`n  === Profile: $prof ===" -ForegroundColor Magenta',
  '    $profDir=Join-Path $OutputDir $prof',
  '    if($AllRegions){',
  '      $rr=& aws @awsFlags ec2 describe-regions --query \'Regions[].RegionName\' --output json 2>&1',
  '      if($LASTEXITCODE -ne 0){Write-Host "  Failed to list regions" -ForegroundColor Red;continue}',
  '      $regions=$rr|ConvertFrom-Json|Sort-Object',
  '      $i=0;$skip=0;foreach($reg in $regions){$i++;$rf=Get-BaseFlags $reg;if(-not(Test-HasResources $rf)){$skip++;continue};Write-Host "  Region $i/$($regions.Count): $reg" -ForegroundColor Cyan',
  '        Export-Region -RegionName $reg -OutPath(Join-Path $profDir $reg)-Parallel $MaxParallel}',
  '      if($skip){Write-Host "  Skipped $skip empty regions" -ForegroundColor DarkGray}',
  '    }else{Export-Region -RegionName $Region -OutPath $profDir -Parallel $MaxParallel}}',
  '}elseif($AllRegions){',
  '  Write-Host "  Mode: All Regions (parallel x$MaxParallel)" -ForegroundColor Cyan',
  '  $rr=& aws @awsFlags ec2 describe-regions --query \'Regions[].RegionName\' --output json 2>&1',
  '  if($LASTEXITCODE -ne 0){Write-Error "Failed: $rr";exit 1}',
  '  $regions=$rr|ConvertFrom-Json|Sort-Object',
  '  if(-not $OutputDir){$ts=Get-Date -Format "yyyyMMdd-HHmmss";$lb=if($Profile){$Profile}else{"default"};$OutputDir="./aws-export-${lb}-allregions-${ts}"}',
  '  New-Item -ItemType Directory -Path $OutputDir -Force|Out-Null',
  '  Write-Host "  $($regions.Count) regions -> $OutputDir`n"',
  '  $i=0;$skip=0;foreach($reg in $regions){$i++;$rf=Get-BaseFlags $reg;if(-not(Test-HasResources $rf)){$skip++;Write-Host "  Region $i/$($regions.Count): $reg — empty, skipping" -ForegroundColor DarkGray;continue};Write-Host "  Region $i/$($regions.Count): $reg" -ForegroundColor Cyan',
  '    Export-Region -RegionName $reg -OutPath(Join-Path $OutputDir $reg)-Parallel $MaxParallel}',
  '  if($skip){Write-Host "  Skipped $skip empty regions" -ForegroundColor DarkGray}',
  '}else{',
  '  if(-not $OutputDir){$ts=Get-Date -Format "yyyyMMdd-HHmmss";$lb=if($Profile){$Profile}else{"default"};$OutputDir="./aws-export-${lb}-${ts}"}',
  '  Write-Host "  Profile: $($Profile ? $Profile : \'default\')  Region: $($Region ? $Region : \'default\')  Output: $OutputDir`n"',
  '  Export-Region -RegionName $Region -OutPath $OutputDir -Parallel $MaxParallel}',
  '$af=Get-ChildItem -Path $OutputDir -Filter "*.json" -Recurse -ErrorAction SilentlyContinue',
  '$fc=($af|Measure-Object).Count;$tb=($af|Measure-Object -Property Length -Sum).Sum',
  '$ts2=if($tb -gt 1MB){"{0:N1} MB" -f($tb/1MB)}elseif($tb -gt 1KB){"{0:N0} KB" -f($tb/1KB)}else{"$tb bytes"}',
  'Write-Host "`n  Done! $fc files ($ts2) -> $OutputDir`n" -ForegroundColor Green'
  ].join('\r\n');
  return script;
}
