// Characterization tests for the report-view helpers extracted from app-core.js
// (Humify decomposition slice). Every assertion pins current behavior.

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { rptSlugify, buildReportHeader, buildReportTOC, buildReportFooter, enabledReportModules } from '../../src/modules/report-view.js';

describe('rptSlugify', () => {
  it('slugifies, strips edge dashes, caps at 60 chars', () => {
    assert.equal(rptSlugify('My Report!'), 'my-report');
    assert.equal(rptSlugify(''), 'report');
    assert.equal(rptSlugify(null), 'report');
    assert.equal(rptSlugify('  --Hello--World--  '), 'hello-world');
    assert.equal(rptSlugify('x'.repeat(80)).length, 60);
  });
});

describe('buildReportHeader', () => {
  it('renders title + subtitle, includes logo when present', () => {
    const h = buildReportHeader({ title: 'Q1 Report', author: 'Schyler', date: '2026-06-01', logo: null });
    assert.ok(h.includes('<h1>Q1 Report</h1>'));
    assert.ok(h.includes('Schyler') && h.includes('2026-06-01') && h.includes('&mdash;'));
    assert.ok(!h.includes('rpt-logo'));
    const withLogo = buildReportHeader({ title: 'T', logo: { dataUri: 'data:image/png;base64,AAA' } });
    assert.ok(withLogo.includes('rpt-logo') && withLogo.includes('data:image/png;base64,AAA'));
    assert.ok(!withLogo.includes('subtitle')); // no author/date
  });
  it('escapes html in the title', () => {
    const h = buildReportHeader({ title: '<script>', author: '', date: '' });
    assert.ok(h.includes('&lt;'));
    assert.ok(!h.includes('<script>'));
  });
  it('defaults the title when absent', () => {
    assert.ok(buildReportHeader({}).includes('AWS Infrastructure Assessment'));
  });
});

describe('buildReportTOC', () => {
  it('numbers enabled modules with anchor links', () => {
    const toc = buildReportTOC(['exec', 'compliance'], [{ id: 'exec', name: 'Executive' }, { id: 'compliance', name: 'Compliance' }]);
    assert.ok(toc.includes('href="#s-exec"'));
    assert.ok(toc.includes('1. Executive'));
    assert.ok(toc.includes('2. Compliance'));
  });
});

describe('buildReportFooter', () => {
  it('renders the footer with the timestamp', () => {
    const f = buildReportFooter('2026-06-01 10:00');
    assert.ok(f.includes('Generated by AWS Mapper'));
    assert.ok(f.includes('2026-06-01 10:00'));
  });
});

describe('enabledReportModules', () => {
  const mods = [
    { id: 'a', enabled: true, available: () => true },
    { id: 'b', enabled: false, available: () => true },
    { id: 'c', enabled: true, available: () => false },
  ];
  it('keeps only enabled + available, default order = registry order', () => {
    assert.deepEqual(enabledReportModules(mods, null), ['a']);
  });
  it('honors a custom order but still filters disabled/unavailable', () => {
    assert.deepEqual(enabledReportModules(mods, ['c', 'a', 'b']), ['a']);
  });
});
